name: RyanDoyle.net
markdown: redcarpet
pygments: true
permalink: /posts/:title/
paginate: 5
paginate_path: "posts/page:num"
deploy_server: serv1.doylenet.net
deploy_path: /data/www/ryandoyle.net/www/
deploy_user: ryan
